services:
  postgres:
    image: postgres:15
    container_name: nivii-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: nivii-admin
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: nivii_db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -h postgres -U nivii-admin"]
      interval: 5s
      timeout: 3s
      retries: 5
    volumes:
      - ./data:/var/lib/postgresql/data
    networks:
      - app-network

  backend:
    build: ./backend
    container_name: nivii-backend
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - ./backend/.env
    environment:
      DATABASE_URL: postgres://nivii-admin:1234@postgres:5432/nivii_db
    volumes:
      - ./backend:/app
    networks:
      - app-network

  frontend:
    build: ./frontend
    container_name: nivii-frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
    environment:
      VITE_API_URL: http://localhost:8000/
    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules
    networks:
      - app-network
    command: sh -c "npm install && npm run dev"

networks:
  app-network:

volumes:
  frontend_node_modules:
